Repository Core-Dynamic-Plus-Labs/Tango-Guard, pull requests merged in 2024-07, with the labels that each got.

#11 Create SECURITY.md
  SECURITY.md
Labels: documentation

#14 Create CODEOWNERS
  .github/CODEOWNERS
Labels: type: enhancement

#13 Update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: priority: low, status: confirmed

#15 Delete .github/workflows directory
  .github/workflows/auto-assign.yml
  .github/workflows/bandit.yml
  .github/workflows/codacy.yml
  .github/workflows/stale.yml
Labels: type: bug, priority: medium

#12 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: priority: high, status: confirmed
